import './global.css';

export const metadata = {
  title: 'Welcome to weather-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-primary-800 text-white">{children}</body>
    </html>
  );
}
